services:

  app:
    build:
      context: ./app
    container_name: dndsearch_app
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/
      - SECRET_KEY=trust_me
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    restart: unless-stopped
    container_name: dndsearch_db
    ports:
      - "27017:27017"